apiVersion: v2
name: pgview
description: A Helm chart for deploying PgView on Kubernetes
type: application
version: 0.10.0
appVersion: "0.10.0"
icon: https://i.ibb.co/CKknLZHj/pgview.png
keywords:
  - pgview
  - postgresql
  - database
home: https://github.com/catwallon/pgview
sources:
  - https://github.com/catwallon/pgview
maintainers:
  - name: catwallon
    url: https://github.com/catwallon
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - kind: changed
      description: Update app to version 0.10.0
