on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - uses: helm/chart-releaser-action@v1.6.0
        id: cr
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Push OCI
        run: |
          helm push .cr-release-packages/pgview-*.tgz oci://ghcr.io/catwallon
